### ISSUE TITLE
包导入问题

### ISSUE THREAD

**Issue by zhangjunfang** [mylxsw/remote-tail#2]
本地运行错误信息如下：
main.go:11:2: cannot find package "command" in any of:
    c:\go\src\command (from $GOROOT)
    C:\workspace\golang\src\command (from $GOPATH)
main.go:10:2: cannot find package "console" in any of:
    c:\go\src\console (from $GOROOT)
    C:\workspace\golang\src\console (from $GOPATH)
建议：
       command 包 修改为：github.com/mylxsw/remote-tail/src/command
       console     包修改为：github.com/mylxsw/remote-tail/src/console

**Comment by mylxsw** [comment]
之前是因为将这个项目放到了其他目录开发，所以需要手动指定编辑器的环境变量，把当前项目目录加入到GOPATH，确实用起来麻烦些，现在改了一下目录结构，按照你的建议调整了一下，更新一下代码再试试
