### ISSUE TITLE
日志文件位置

### ISSUE THREAD

**Issue by zhangjunfang** [mylxsw/remote-tail#3]
建议：
       日志文件位置，可能在时间环境中不是相同的位置。建议数据结构设计为： 目标主机与日志文件位置对应更合理。

**Comment by mylxsw** [comment]
不同主机使用不同的日志文件位置是支持的，需要使用`-conf`参数指定配置文件，参考 [指定配置文件](https://github.com/mylxsw/remote-tail#指定配置文件)，配置文件参考 [example.toml](https://github.com/mylxsw/remote-tail/blob/master/example.toml)。
