### ISSUE TITLE
用go太复杂了

### ISSUE THREAD

**Issue by XLPE** [mylxsw/remote-tail#7]
其实用shell就够了，如果没有跳板机，直接用ssh &就可以达到多进程登陆多台机器执行tail命令的目的；如果有跳板机，则用ssh ProxyCommand在跳板机上用nc建立一个代理，然后登陆

**Comment by mylxsw** [comment]
用shell也可以实现，其实原理是很简单的，就是ssh到服务器，然后执行`tail -f`，最后将输出聚合到一起输出就可以 ，用Go来做主要是考虑到打包成二进制文件后，使用起来更加方便一些
