### ISSUE TITLE
有没有将不同服务器日志合并保存在指定服务器上的功能?

### ISSUE THREAD

**Issue by LiangWeiCheng** [mylxsw/remote-tail#8]
有没有将不同服务器日志合并保存在指定服务器上的功能?

**Comment by mylxsw** [comment]
最新发布的release可以这样实现

    nohup remote-tail -hosts 'watcher@192.168.1.226,watcher@192.168.1.225' -file '/usr/local/openresthy/nginx/logs/access.log' -slient=true > ./res.log &
