### ISSUE TITLE
如果日志文件名称全都包含时间戳，配置文件要如何匹配最新日志文件呢？

### ISSUE THREAD

**Issue by graveskeeper** [mylxsw/remote-tail#9]
例如目录下有sc-2017-08-25.log、sc-2017-08-24.log、sc-2017-08-23.log......如下规则的日志
为了显示日志我写了类似如下的配置文件：
```
[servers.1]
hostname="10.0.0.1"
user="root"
tail_file="/var/log/php-fpm/sc-*.log"
```
这样写虽然能用，但是当文件数量很多时候这么做很浪费内存和执行时间。
怎么写配置文件才可以只关注最新日期的日志，是否有可以支持shell命令或其它参数的方法取到最新的日志文件？

**Comment by mylxsw** [comment]
tail_file参数是支持加入shell命令参数的，比如你这个可以这样试试

`tail_file="/var/log/php-fpm/sc-$(date +%Y-%m-%d).log"`
